# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pre-release:
    # The type of runner that the job will run on
    name: "Pre Release"
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{  secrets.GITHUB_TOKEN  }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            localrepo/x86_64/essentials.files
            localrepo/x86_64/essentials.db
            localrepo/x86_64/essentials.db.tar.gz
            localrepo/x86_64/essentials.files.tar.gz
            localrepo/x86_64/*.pkg.tar.zst
