
name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pre-release:
    name: "Latest Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{  secrets.GITHUB_TOKEN  }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Release Build"
          files: |
            LICENSE.txt
            localrepo/x86_64/essentials.files
            localrepo/x86_64/essentials.db
            localrepo/x86_64/essentials.db.tar.gz
            localrepo/x86_64/essentials.files.tar.gz
            localrepo/x86_64/*.pkg.tar.zst
